# Generated by Django 5.2.4 on 2025-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name="В подборке 'Наш Выбор'?"),
        ),
    ]
